activity_state:
  unfollow: "unfollow"
  follow: "follow"
  learned: "learned"
user:
  avatar_size: 50
  small_size: 20
  password:
    minimum_characters: 6
lessons:
  words_per_lesson: 20
activities:
  per_page: 5
category_type:
  all: "all_words"
  learned: "learned"
  not_learned: "not_learned"
word:
  minimum_answers: 4
  audio:
    allow_type: ["wav", "mp3"]
    allow_mime: "audio/wav,audio/mp3"
store_dir: "uploads"
