activity_state:
  unfollow: "unfollow"
  follow: "follow"
  learned: "learned"
user:
  avatar_size: 50
  small_size: 20
lessons:
  words_per_lesson: 20
activities:
  per_page: 5
category_type:
  all: "all"
  learned: "learned"
  not_learned: "not_learned"
word:
  minimum_answers: 4
