activity_state:
  unfollow: "unfollow"
  follow: "follow"
  learned: "learned"
user:
  avatar_size: 50
lessons:
  words_per_lesson: 20
category_type:
  all: "all"
  learned: "learned"
  not_learned: "not_learned"
